/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481Hw1Part2;

import java.util.ArrayList;
import jdk.nashorn.internal.runtime.ECMAErrors;


public class App {
    public static int sumOfNumbersInIndeces(ArrayList<Integer> array, int firstIndex, int secondIndex)throws Exception{
        System.out.println("inside search");

        if (array == null){
            throw new Exception("Array is null.");
        }
        else if(array.size() <= Math.max(firstIndex, secondIndex) ){
            throw new Exception("Index out of bound.");
        }
        else{
            return array.get(firstIndex) + array.get(secondIndex);
        }
      }


    public static void main(String[] args) {
        ArrayList<Integer> a = new ArrayList<Integer>();
        for(int i = 0 ; i<10; i++){
            a.add(i);
        }

        //System.out.println("sumOfNumbersInIndeces(a, 1, 2): "+sumOfNumbersInIndeces(a, 1, 2));
    }
}