/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481Hw1Part2;

import java.util.ArrayList;
import org.junit.jupiter.api.Test;



import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void arrayNullTest() {
        assertThrows(
				Exception.class,
				() -> { App.sumOfNumbersInIndeces(null, 2, 1); });
    }
    @Test void arraySizeTest() {
        ArrayList<Integer> a = new ArrayList<Integer>();
        for(int i = 0 ; i<10; i++){
            a.add(i);
        }
        assertThrows(
				Exception.class,
                () -> { App.sumOfNumbersInIndeces(a, 22, 1); });

        ArrayList<Integer> b= new ArrayList<Integer>();        
        assertThrows(
				Exception.class,
                () -> { App.sumOfNumbersInIndeces(b, 0, 0); });
        
    }
    @Test void emptyArrayTest() {

        ArrayList<Integer> b= new ArrayList<Integer>();        
        assertThrows(
				Exception.class,
                () -> { App.sumOfNumbersInIndeces(b, 0, 0); });
        
    }
    @Test void largeIntegerTest() {
        ArrayList<Integer> a = new ArrayList<Integer>();
        
        a.add(100000);
        a.add(200000);
        
        try{
        assertEquals(300000,App.sumOfNumbersInIndeces(a, 1, 0));
        }catch(Exception e){

        }
    }
    @Test void correctInputTest() {
        ArrayList<Integer> a = new ArrayList<Integer>();
        for(int i = 0 ; i<10; i++){
            a.add(i);
        }
        try{
        assertEquals(3,App.sumOfNumbersInIndeces(a, 1, 2));
        }catch(Exception e){

        }
    }
}
